### ISSUE TITLE
fatal error: moveit/collision_distance_field/collision_robot_hybrid.h: No such file or directory

### ISSUE THREAD

**Issue by jstmn** [cheulkang/TORM#2]
Hi, I'm running `catkin_make` and am getting the following error:

```
####
#### Running command: "make cmake_check_build_system" in "/home/jstm/ros/torm_ws/build"
####
####
#### Running command: "make -j16 -l16" in "/home/jstm/ros/torm_ws/build"
####
[ 14%] Built target joystick_teleop
[ 28%] Built target fetch_arm_moveit_ikfast_plugin
[ 35%] Building CXX object TORM/CMakeFiles/torm.dir/src/torm_optimizer.cpp.o
In file included from /home/jstm/ros/torm_ws/src/TORM/src/torm_optimizer.cpp:40:
/home/jstm/ros/torm_ws/src/TORM/include/torm/torm_optimizer.h:47:10: fatal error: moveit/collision_distance_field/collision_robot_hybrid.h: No such file or directory
   47 | #include <moveit/collision_distance_field/collision_robot_hybrid.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [TORM/CMakeFiles/torm.dir/build.make:102: TORM/CMakeFiles/torm.dir/src/torm_optimizer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3334: TORM/CMakeFiles/torm.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j16 -l16" failed
``` 
I looked up this error and didn't see anything online. However I found `collision_robot_hybrid.h` in the moveit documentation here: http://docs.ros.org/en/kinetic/api/moveit_core/html/collision__robot__hybrid_8h.html. However that documentation is for ros `kinetic` and i'm on `noetic`. I am unable to install ros `kinetic` fwiw. 

I'm running:
- Ubuntu 20.04
- ros noetic
My ros workspace consists of this package and the `fetch_ros` package https://github.com/ZebraDevs/fetch_ros in src/

How can I resolve this error?

Thanks

**Comment by cheulkang** [comment]
I used the ROS melodic version of moveit.

I checked the ROS noetic version of moveit. 
"moveit/collision_distance_field/collision_robot_hybrid.h"  is removed.

I think that the moveit is updated as the ROS version changes.
I'll update this package to match the noetic version.

**Comment by jstmn** [comment]
Hi, checking on this! I'm on ubuntu 20 so melodic is unavailable. 

Thanks

**Comment by cheulkang** [comment]
I uploaded the noetic version of TORM.
Please check it.

**Comment by jstmn** [comment]
Thanks! it's working now
